---
language: ruby
sudo: false
bundler_args: --without development
cache: bundler
rvm:
  - 1.9.3
  - 2.1.0
env:
  - PUPPET_LOCATION="~> 3.7.0" PARSER="future"
  - PUPPET_LOCATION="~> 3.7.0"
  - PUPPETFILE_DIR="vendor/modules"
before_script:
  - bundle exec r10k --verbose 3 puppetfile install
script:
  - bundle exec rake test
  - bundle exec puppet apply --test --noop --modulepath=$PUPPETFILE_DIR tests/init.pp 
notifications:
  email: false
  slack:
    secure: IEpthWx2hFDiQrLDIdfieDDVfte3hKGFaFDvBT8DHk7JQnX0LeABzkA7OBrI1mcXvToCmInwLCje73pEAP59f6v+yYToGenwb8b6xlGHEzAnbuYYgL0IlcY+v6M1ze/NsS+2YS/3QAfBgQhfxQPW9XRocfDH3WZBR2YeUQp1ip0=
