language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0

before_script:
  - r10k puppetfile install

script:
  - bundle exec rake test
  - puppet apply --test --noop --modulepath=./modules tests/init.pp 

notifications:
  slack:
    secure: IEpthWx2hFDiQrLDIdfieDDVfte3hKGFaFDvBT8DHk7JQnX0LeABzkA7OBrI1mcXvToCmInwLCje73pEAP59f6v+yYToGenwb8b6xlGHEzAnbuYYgL0IlcY+v6M1ze/NsS+2YS/3QAfBgQhfxQPW9XRocfDH3WZBR2YeUQp1ip0=
